/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Shield, Skull, Search, Users, Sun, HelpCircle, Flame, Swords, Zap, CheckCircle } from 'lucide-react';
import { translations, getLocalizedRoleDetails } from '../../utils/translations';
import { RoleType } from '../../types';
import { sfx } from '../../utils/audio';

interface HowToPlayProps {
  onBack: () => void;
  language: 'en' | 'ar';
}

export const HowToPlay: React.FC<HowToPlayProps> = ({ onBack, language }) => {
  const t = translations[language];
  const isRtl = language === 'ar';

  const citizen = getLocalizedRoleDetails(RoleType.CITIZEN, language);
  const mafia = getLocalizedRoleDetails(RoleType.MAFIA, language);
  const doctor = getLocalizedRoleDetails(RoleType.DOCTOR, language);
  const detective = getLocalizedRoleDetails(RoleType.DETECTIVE, language);

  return (
    <div 
      className="w-full max-w-4xl mx-auto px-4 py-8 text-slate-100 fade-in"
      style={{ direction: isRtl ? 'rtl' : 'ltr' }}
    >
      <div className="flex items-center justify-between mb-8 border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center shadow-[0_0_10px_rgba(59,130,246,0.3)]">
            <HelpCircle className="w-4.5 h-4.5 text-white" />
          </div>
          <h1 className="text-2xl font-black tracking-tight font-display text-white">
            {isRtl ? 'دليل كيف تلعب مافيا' : 'How To Play Mafia'}
          </h1>
        </div>
        <button
          onClick={() => { sfx.playClick(); onBack(); }}
          className="text-xs font-bold px-4 py-2 rounded-lg bg-slate-900/50 hover:bg-slate-800 border border-slate-800 text-slate-300 transition-all cursor-pointer font-mono"
        >
          {isRtl ? 'العودة للرئيسية' : 'BACK TO MENU'}
        </button>
      </div>

      <div className="space-y-10 font-medium">
        
        {/* Section 1: What is Mafia? / ما هي المافيا؟ */}
        <div className="bg-[#1E293B] border border-slate-750 p-6 rounded-2xl shadow-md">
          <h2 className="text-lg font-bold text-blue-400 mb-4 flex items-center gap-2 font-display">
            <Users className="w-5 h-5" />
            {isRtl ? '١. ما هي المافيا؟' : '1. What is Mafia?'}
          </h2>
          <p className="text-sm text-slate-300 leading-relaxed">
            {isRtl 
              ? 'لعبة المافيا هي لعبة رعب نفسية وتزييف اجتماعي للمجموعات. تنقسم المدينة إلى جبهتين سريتين: أهل المدينة الشرفاء، والمافيا المتسللين. المشكلة؟ الشرفاء لا يعرفون هويات بعضهم البعض، بينما المافيا يعرفون بعضهم ويتعاونون سراً للقضاء على المدينة بالتوالي.'
              : 'Mafia is a social deduction game of trust, betrayal, and survival. A sleepy village is infiltrated by secret Mafia members. The catch? The innocent townspeople do not know who to trust, while the Mafia members know each other and coordinate secretly to eliminate everyone else.'}
          </p>
        </div>

        {/* Section 2: Setup (30 seconds) / الإعداد (30 ثانية) */}
        <div className="bg-[#1E293B] border border-slate-750 p-6 rounded-2xl shadow-md">
          <h2 className="text-lg font-bold text-purple-400 mb-4 flex items-center gap-2 font-display">
            <Zap className="w-5 h-5" />
            {isRtl ? '٢. الإعداد (٣٠ ثانية)' : '2. Setup (30 seconds)'}
          </h2>
          <p className="text-sm text-slate-300 leading-relaxed mb-4">
            {isRtl 
              ? 'تم تصميم نسختنا لتلعب بدون بطاقات حقيقية وبدون أي تجهيزات معقدة. كل ما تحتاجه هو هاتف واحد فقط ومجموعة من الأصدقاء في الغرفة:'
              : 'Our platform is fully customized to start a game offline on a single device in less than a minute. No cards or complex rule sheets required:'}
          </p>
          <ul className={`space-y-2 text-xs text-slate-400 ${isRtl ? 'list-disc pr-5' : 'list-disc pl-5'}`}>
            <li>
              <strong>{isRtl ? 'عدد اللاعبين:' : 'Player Count:'}</strong>{' '}
              {isRtl ? 'من ٤ إلى ٢٠ لاعباً كحد أقصى.' : 'Configure 4 to 20 players directly.'}
            </li>
            <li>
              <strong>{isRtl ? 'تسمية سريعة مضحكة:' : 'Funny Autogenerated Names:'}</strong>{' '}
              {isRtl ? 'يتكفل النظام بملء أسماء الأصدقاء تلقائياً بأسماء طريفة لتوفير وقت الكتابة!' : 'Let the system autogenerate funny default names so you do not waste time typing.'}
            </li>
            <li>
              <strong>{isRtl ? 'موازنة الأدوار التلقائية:' : 'Smart Role Balancer:'}</strong>{' '}
              {isRtl ? 'يقوم المحرك الرياضي باحتساب التوازن العادل للأدوار وتعيين عدد المافيا والأطباء والمحققين المثالي تلقائياً تبعاً لعددكم.' : 'Our mathematical balancer automatically guarantees the perfect challenge by adjusting Doctor, Detective, and Mafia quotas for your size.'}
            </li>
          </ul>
        </div>

        {/* Section 3: The Roles / الأدوار */}
        <div>
          <h2 className="text-lg font-bold text-emerald-400 mb-5 flex items-center gap-2 font-display">
            <Flame className="w-5 h-5" />
            {isRtl ? '٣. الأدوار' : '3. The Roles'}
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {/* Citizen */}
            <div className="bg-[#1E293B] border border-blue-900/20 p-5 rounded-2xl hover:border-blue-500/40 transition-all shadow-sm">
              <div className="w-10 h-10 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-400 mb-4">
                <Users className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold text-blue-400 font-display">{citizen.name}</h3>
              <p className="text-[10px] text-slate-500 mt-1 uppercase tracking-wider font-mono font-bold">
                {isRtl ? 'الفريق: أهل القرية' : 'Team: Town'}
              </p>
              <p className="text-xs text-slate-300 mt-3 leading-relaxed">
                {citizen.description}
              </p>
            </div>

            {/* Mafia */}
            <div className="bg-[#1E293B] border border-red-900/20 p-5 rounded-2xl hover:border-red-500/40 transition-all shadow-sm">
              <div className="w-10 h-10 rounded-lg bg-red-500/10 flex items-center justify-center text-red-400 mb-4">
                <Skull className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold text-red-400 font-display">{mafia.name}</h3>
              <p className="text-[10px] text-slate-500 mt-1 uppercase tracking-wider font-mono font-bold">
                {isRtl ? 'الفريق: المافيا' : 'Team: Mafia'}
              </p>
              <p className="text-xs text-slate-300 mt-3 leading-relaxed">
                {mafia.description}
              </p>
            </div>

            {/* Doctor */}
            <div className="bg-[#1E293B] border border-emerald-900/20 p-5 rounded-2xl hover:border-emerald-500/40 transition-all shadow-sm">
              <div className="w-10 h-10 rounded-lg bg-emerald-500/10 flex items-center justify-center text-emerald-400 mb-4">
                <Shield className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold text-emerald-400 font-display">{doctor.name}</h3>
              <p className="text-[10px] text-slate-500 mt-1 uppercase tracking-wider font-mono font-bold">
                {isRtl ? 'الفريق: أهل القرية' : 'Team: Town'}
              </p>
              <p className="text-xs text-slate-300 mt-3 leading-relaxed">
                {doctor.description}
              </p>
            </div>

            {/* Detective */}
            <div className="bg-[#1E293B] border border-amber-900/20 p-5 rounded-2xl hover:border-amber-500/40 transition-all shadow-sm">
              <div className="w-10 h-10 rounded-lg bg-amber-500/10 flex items-center justify-center text-amber-400 mb-4">
                <Search className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold text-amber-400 font-display">{detective.name}</h3>
              <p className="text-[10px] text-slate-500 mt-1 uppercase tracking-wider font-mono font-bold">
                {isRtl ? 'الفريق: أهل القرية' : 'Team: Town'}
              </p>
              <p className="text-xs text-slate-300 mt-3 leading-relaxed">
                {detective.description}
              </p>
            </div>
          </div>
        </div>

        {/* Section 4: Game Phases / مراحل اللعبة */}
        <div className="bg-[#1E293B] border border-slate-750 p-6 rounded-2xl shadow-md">
          <h2 className="text-lg font-bold text-amber-500 mb-4 flex items-center gap-2 font-display">
            <Sun className="w-5 h-5 text-amber-400" />
            {isRtl ? '٤. مراحل اللعبة' : '4. Game Phases'}
          </h2>
          <div className="space-y-4">
            <div className={`relative ${isRtl ? 'border-r-2 pr-4' : 'border-l-2 pl-4'} border-slate-800 space-y-4`}>
              <div className="relative">
                <div className={`absolute ${isRtl ? '-right-[21px]' : '-left-[21px]'} top-1 w-2.5 h-2.5 rounded-full bg-blue-500`}></div>
                <h4 className="text-xs font-bold text-blue-400 uppercase tracking-wider">{isRtl ? '١. الكشف السري' : '1. Secret Reveal'}</h4>
                <p className="text-xs text-slate-400 mt-0.5 leading-relaxed">
                  {isRtl ? 'يمرر الهاتف للاعبين بالتوالي. يقوم كل لاعب بلمس الشاشة مطولاً لمعرفة هويته دون تسريب للآخرين.' : 'Pass the phone around. Each player holds down the screen to securely see their assignment.'}
                </p>
              </div>
              <div className="relative">
                <div className={`absolute ${isRtl ? '-right-[21px]' : '-left-[21px]'} top-1 w-2.5 h-2.5 rounded-full bg-red-500`}></div>
                <h4 className="text-xs font-bold text-red-400 uppercase tracking-wider">{isRtl ? '٢. الليل الفعلي (أفعال الأدوار)' : '2. Night Phase'}</h4>
                <p className="text-xs text-slate-400 mt-0.5 leading-relaxed">
                  {isRtl ? 'يغمض الجميع عيونهم. يستلم القائد الهاتف ليمرر لغة الليل: تختار المافيا ضحيتها، يختار الطبيب المريض لحمايته، ويحقق المحقق في هوية أحد المشتبهين.' : 'Active roles execute their turn in secrecy: Mafia coordinates an assassination, the Doctor saves a chosen life, and the Detective audits a player.'}
                </p>
              </div>
              <div className="relative">
                <div className={`absolute ${isRtl ? '-right-[21px]' : '-left-[21px]'} top-1 w-2.5 h-2.5 rounded-full bg-emerald-500`}></div>
                <h4 className="text-xs font-bold text-emerald-400 uppercase tracking-wider">{isRtl ? '٣. النهار والمناقشة' : '3. Morning Discussion'}</h4>
                <p className="text-xs text-slate-400 mt-0.5 leading-relaxed">
                  {isRtl ? 'يستيقظ الجميع نهاراً. يعلن الهاتف ضحية الليل (إن وجد). يبدأ الجميع بالنقاش وتبادل الاتهامات تحت ضغط مؤقت الثواني.' : 'The host reveals who died at night (if anyone). The town debates who looks suspicious using a dynamic countdown timer.'}
                </p>
              </div>
              <div className="relative">
                <div className={`absolute ${isRtl ? '-right-[21px]' : '-left-[21px]'} top-1 w-2.5 h-2.5 rounded-full bg-amber-500`}></div>
                <h4 className="text-xs font-bold text-amber-400 uppercase tracking-wider">{isRtl ? '٤. التصويت والإقصاء' : '4. Voting Banishment'}</h4>
                <p className="text-xs text-slate-400 mt-0.5 leading-relaxed">
                  {isRtl ? 'يجري تصويت علني أو سري على المشتبهين. اللاعب الذي يحصل على أغلبية الأصوات يطرد وتكشف هويته للجميع.' : 'Players vote to execute a primary suspect. The majority vote banishes that player, revealing their real role.'}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Section 5: Win Conditions / شروط الفوز */}
        <div className="bg-[#1E293B] border border-slate-750 p-6 rounded-2xl shadow-md">
          <h2 className="text-lg font-bold text-indigo-400 mb-4 flex items-center gap-2 font-display">
            <Swords className="w-5 h-5 text-indigo-400" />
            {isRtl ? '٥. شروط الفوز' : '5. Win Conditions'}
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            <div className="bg-[#0A0F1D]/40 p-4 rounded-xl border border-blue-950/40">
              <p className="font-bold text-blue-400 text-xs flex items-center gap-1.5">
                <CheckCircle className="w-4 h-4 shrink-0 text-blue-400" />
                {isRtl ? 'فوز الشرفاء (البلدة)' : 'Town Victory'}
              </p>
              <p className="text-slate-400 mt-2 leading-relaxed">
                {isRtl ? 'ينتصر أهل القرية الشرفاء فور نجاحهم في كشف وإقصاء جميع أعضاء المافيا بالكامل.' : 'The Town wins the instant all active Mafia members are successfully identified and banished.'}
              </p>
            </div>
            <div className="bg-[#0A0F1D]/40 p-4 rounded-xl border border-red-950/40">
              <p className="font-bold text-red-400 text-xs flex items-center gap-1.5">
                <CheckCircle className="w-4 h-4 shrink-0 text-red-400" />
                {isRtl ? 'فوز المافيا' : 'Mafia Victory'}
              </p>
              <p className="text-slate-400 mt-2 leading-relaxed">
                {isRtl ? 'تنتصر المافيا فوراً إذا تساوى عدد أعضاء المافيا الأحياء مع عدد الشرفاء الأحياء (أو فاقوهم عدداً).' : 'The Mafia wins the moment their numbers equal or exceed the surviving Townspeople.'}
              </p>
            </div>
          </div>
        </div>

        {/* Section 6: Tips for Beginners / نصائح للمبتدئين */}
        <div className="bg-[#1E293B] border border-slate-750 p-6 rounded-2xl shadow-md">
          <h2 className="text-lg font-bold text-amber-400 mb-4 flex items-center gap-2 font-display">
            💡
            {isRtl ? '٦. نصائح وحيل للمبتدئين' : '6. Tips for Beginners'}
          </h2>
          <ul className="space-y-3 text-xs text-slate-300 leading-relaxed">
            <li className="flex items-start gap-2">
              <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-1.5 shrink-0"></div>
              <span>
                <strong>{isRtl ? 'غطِّ الشاشة بالكامل:' : 'Cover Your Screen:'}</strong>{' '}
                {isRtl ? 'عند تمرير الهاتف لرفيقك، تأكد من عدم تطفل الجالسين بجانبك لحماية سرية هويتك وجولتك.' : 'When passing the device, shelter the display from adjacent players to ensure total stealth.'}
              </span>
            </li>
            <li className="flex items-start gap-2">
              <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-1.5 shrink-0"></div>
              <span>
                <strong>{isRtl ? 'الضغط المطول ذكي:' : 'Use the Long Press:'}</strong>{' '}
                {isRtl ? 'تم ابتكار حاجز الضغط المطول لمنع الفتح العرضي لبطاقة الهوية أثناء نقل الهاتف من يد لأخرى.' : 'Our continuous touch screen unlock prevents accidental peeking during transfers.'}
              </span>
            </li>
            <li className="flex items-start gap-2">
              <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-1.5 shrink-0"></div>
              <span>
                <strong>{isRtl ? 'استراتيجية الطبيب:' : 'Predict as Doctor:'}</strong>{' '}
                {isRtl ? 'لا تحمِ نفسك في كل مرة بشكل عشوائي! حاول التنبؤ بلاعب البلدة الذكي الذي تود المافيا إسكاته وقم بحمايته سرياً.' : 'Try to predict who the Mafia perceives as their biggest threat and protect them from demise.'}
              </span>
            </li>
            <li className="flex items-start gap-2">
              <div className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-1.5 shrink-0"></div>
              <span>
                <strong>{isRtl ? 'تضليل المحقق:' : 'Whisper as Detective:'}</strong>{' '}
                {isRtl ? 'إذا كشفت عضو مافيا، لا تعلن هويتك بصوت عالٍ فوراً لكيلا تغتالك المافيا الليلة التالية. وجه المناقشة نحوهم بحجج مضللة ذكية.' : 'If you find a Mafia member, guide the discussion towards executing them without painting a target on yourself.'}
              </span>
            </li>
          </ul>
        </div>

      </div>

      <div className="mt-12 text-center">
        <button
          onClick={() => { sfx.playClick(); onBack(); }}
          className="px-8 py-4 bg-blue-600 hover:bg-blue-500 text-white font-extrabold rounded-2xl shadow-xl shadow-blue-950/40 hover:shadow-blue-500/20 active:scale-95 transition-all cursor-pointer uppercase font-mono tracking-wider"
        >
          {isRtl ? 'فهمت، لنبدأ اللعب!' : "Got It, Let's Play!"}
        </button>
      </div>
    </div>
  );
};
